# This role serve migration/upgrade purposes, cos it takes the backup from
# master instance rather the slave (which is default for regular backup).
# It allows to make master-master replication between new and old revisions
- hosts: localhost
  gather_facts: no
  tasks:
  - debug: var=groups

- hosts: _role_master
  gather_facts: yes
  remote_user: ansible
  become: true
  vars_files:
    - "vars/common.yaml"
  tasks:
  - name: Trigger MySQL backup creation with xtrabackup
    async: 86400
    poll: 0 # Further reading https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html#run-tasks-concurrently-poll-0
    command: xtrabackup_backup_create
    environment:
      MYSQL_PWD: "{{ mysql_root_password }}"
