# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
steps:
  - name: 'gcr.io/cloud-builders/wget'
    args: ["https://releases.hashicorp.com/packer/${_PACKER_VERSION}/packer_${_PACKER_VERSION}_linux_amd64.zip"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}',
           '-t', 'gcr.io/$PROJECT_ID/packer',
           '-t', 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}',
           '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
           '--build-arg', 'PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}',
           '.']
substitutions:
  # Take from https://releases.hashicorp.com/packer
  _PACKER_VERSION: 1.9.4
  _PACKER_VERSION_SHA256SUM: 6cd5269c4245aa8c99e551d1b862460d63fe711c58bec618fade25f8492e80d9

images:
  - 'gcr.io/$PROJECT_ID/packer:latest'
  - 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}'
tags: ['cloud-builders-community', 'packer']
