- name: ensure mysql is running
  service: name=mysql state=started

- name: update root user with the password on the first run
  community.mysql.mysql_user:
    login_password: None
    login_user: root
    check_implicit_admin: true
    update_password: always
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  when: data_filesystem.changed

- name: Add root .env file
  template:
    src: root_env.j2
    dest: "/root/.env"

- name: load .env file for root
  lineinfile:
    state: present
    path: "/root/.bashrc"
    line: "export $(cat /root/.env)"
